spring:
  datasource:
    url: "jdbc:h2:~/test"
    username: "sa"
    password: ""

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}

    jwt:
      secret: ${JWT_SECRET}
